# Generated by Django 6.0.6 on 2026-07-09 04:48

import django_cryptography.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='passport_number',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=50)),
        ),
    ]
