# Generated by Django 6.0.6 on 2026-07-09 05:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_alter_customer_passport_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='emergency_contact_country_code',
            field=models.CharField(blank=True, choices=[('+93', 'Afghanistan (+93)'), ('+355', 'Albania (+355)'), ('+213', 'Algeria (+213)'), ('+376', 'Andorra (+376)'), ('+244', 'Angola (+244)'), ('+54', 'Argentina (+54)'), ('+374', 'Armenia (+374)'), ('+61', 'Australia (+61)'), ('+43', 'Austria (+43)'), ('+994', 'Azerbaijan (+994)'), ('+973', 'Bahrain (+973)'), ('+880', 'Bangladesh (+880)'), ('+375', 'Belarus (+375)'), ('+32', 'Belgium (+32)'), ('+501', 'Belize (+501)'), ('+975', 'Bhutan (+975)'), ('+591', 'Bolivia (+591)'), ('+387', 'Bosnia and Herzegovina (+387)'), ('+267', 'Botswana (+267)'), ('+55', 'Brazil (+55)'), ('+673', 'Brunei (+673)'), ('+359', 'Bulgaria (+359)'), ('+855', 'Cambodia (+855)'), ('+237', 'Cameroon (+237)'), ('+1', 'Canada (+1)'), ('+56', 'Chile (+56)'), ('+86', 'China (+86)'), ('+57', 'Colombia (+57)'), ('+506', 'Costa Rica (+506)'), ('+385', 'Croatia (+385)'), ('+53', 'Cuba (+53)'), ('+357', 'Cyprus (+357)'), ('+420', 'Czech Republic (+420)'), ('+45', 'Denmark (+45)'), ('+20', 'Egypt (+20)'), ('+372', 'Estonia (+372)'), ('+251', 'Ethiopia (+251)'), ('+679', 'Fiji (+679)'), ('+358', 'Finland (+358)'), ('+33', 'France (+33)'), ('+995', 'Georgia (+995)'), ('+49', 'Germany (+49)'), ('+233', 'Ghana (+233)'), ('+30', 'Greece (+30)'), ('+502', 'Guatemala (+502)'), ('+852', 'Hong Kong (+852)'), ('+36', 'Hungary (+36)'), ('+354', 'Iceland (+354)'), ('+91', 'India (+91)'), ('+62', 'Indonesia (+62)'), ('+98', 'Iran (+98)'), ('+964', 'Iraq (+964)'), ('+353', 'Ireland (+353)'), ('+972', 'Israel (+972)'), ('+39', 'Italy (+39)'), ('+81', 'Japan (+81)'), ('+962', 'Jordan (+962)'), ('+7', 'Kazakhstan (+7)'), ('+254', 'Kenya (+254)'), ('+965', 'Kuwait (+965)'), ('+856', 'Laos (+856)'), ('+371', 'Latvia (+371)'), ('+961', 'Lebanon (+961)'), ('+218', 'Libya (+218)'), ('+423', 'Liechtenstein (+423)'), ('+370', 'Lithuania (+370)'), ('+352', 'Luxembourg (+352)'), ('+853', 'Macau (+853)'), ('+60', 'Malaysia (+60)'), ('+960', 'Maldives (+960)'), ('+356', 'Malta (+356)'), ('+52', 'Mexico (+52)'), ('+377', 'Monaco (+377)'), ('+976', 'Mongolia (+976)'), ('+382', 'Montenegro (+382)'), ('+212', 'Morocco (+212)'), ('+95', 'Myanmar (+95)'), ('+977', 'Nepal (+977)'), ('+31', 'Netherlands (+31)'), ('+64', 'New Zealand (+64)'), ('+234', 'Nigeria (+234)'), ('+47', 'Norway (+47)'), ('+968', 'Oman (+968)'), ('+92', 'Pakistan (+92)'), ('+507', 'Panama (+507)'), ('+595', 'Paraguay (+595)'), ('+51', 'Peru (+51)'), ('+63', 'Philippines (+63)'), ('+48', 'Poland (+48)'), ('+351', 'Portugal (+351)'), ('+974', 'Qatar (+974)'), ('+40', 'Romania (+40)'), ('+7', 'Russia (+7)'), ('+250', 'Rwanda (+250)'), ('+966', 'Saudi Arabia (+966)'), ('+381', 'Serbia (+381)'), ('+65', 'Singapore (+65)'), ('+421', 'Slovakia (+421)'), ('+386', 'Slovenia (+386)'), ('+27', 'South Africa (+27)'), ('+82', 'South Korea (+82)'), ('+34', 'Spain (+34)'), ('+94', 'Sri Lanka (+94)'), ('+249', 'Sudan (+249)'), ('+46', 'Sweden (+46)'), ('+41', 'Switzerland (+41)'), ('+886', 'Taiwan (+886)'), ('+255', 'Tanzania (+255)'), ('+66', 'Thailand (+66)'), ('+216', 'Tunisia (+216)'), ('+90', 'Turkey (+90)'), ('+256', 'Uganda (+256)'), ('+380', 'Ukraine (+380)'), ('+971', 'United Arab Emirates (+971)'), ('+44', 'United Kingdom (+44)'), ('+1', 'United States (+1)'), ('+598', 'Uruguay (+598)'), ('+998', 'Uzbekistan (+998)'), ('+58', 'Venezuela (+58)'), ('+84', 'Vietnam (+84)'), ('+967', 'Yemen (+967)'), ('+260', 'Zambia (+260)'), ('+263', 'Zimbabwe (+263)')], default='+94', max_length=5),
        ),
        migrations.AlterField(
            model_name='customer',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message='Enter exactly 10 digits, without the country code (e.g. 0771234567 or 7712345678).', regex='^\\d{10}$')]),
        ),
    ]
