# Generated by Django 6.0.6 on 2026-07-04 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='profile/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
